schedule:
  trigger_time: "09:35:00"

notification:
  sendkey: ""
  email:
    to: "494256683@qq.com"
    smtp_user: "494256683@qq.com"
    smtp_pass: "geuzphtdcwcsbiia"

funds:
  etf:
    - "513500"
    - "513650"
    - "159612"
    - "159655"

  index:
    - "050025"
    - "161125"
    - "018064"
    - "007721"
    - "017028"
    - "017641"

data_sources:
  eastmoney: "https://fund.eastmoney.com"
